{
  "name": "SemanticModel",
  "compatibilityLevel": 1500,
  "model": {
    "culture": "en-US",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/192 168 65 11;automationdw",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "192.168.65.11",
            "database": "automationdw"
          },
          "authentication": null,
          "query": null
        },
        "options": {},
        "credential": {
          "AuthenticationKind": "Windows",
          "kind": "SQL",
          "path": "192.168.65.11;automationdw",
          "Username": "BI-SSAS@mobinsb.net",
          "EncryptConnection": false
        }
      },
      {
        "type": "structured",
        "name": "SQL/192 168 65 11;TempHistorical",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "192.168.65.11",
            "database": "TempHistorical"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "Windows",
          "kind": "SQL",
          "path": "192.168.65.11;TempHistorical",
          "Username": "BI-SSAS@mobinsb.net",
          "EncryptConnection": false
        }
      },
      {
        "type": "structured",
        "name": "SQL/192 168 65 11;rawdb",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "192.168.65.11",
            "database": "rawdb"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "Windows",
          "kind": "SQL",
          "path": "192.168.65.11;rawdb",
          "Username": "BI-SSAS@mobinsb.net",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "DimCustomer",
        "columns": [
          {
            "name": "CustomerId",
            "dataType": "int64",
            "sourceColumn": "CustomerId"
          },
          {
            "name": "PersonId",
            "dataType": "int64",
            "sourceColumn": "PersonId"
          },
          {
            "name": "ClubMemberId",
            "dataType": "int64",
            "sourceColumn": "ClubMemberId"
          },
          {
            "name": "IsClubMember",
            "dataType": "int64",
            "sourceColumn": "IsClubMember"
          },
          {
            "name": "IsClubMemberName",
            "dataType": "string",
            "sourceColumn": "IsClubMemberName"
          },
          {
            "name": "IsFromSejam",
            "dataType": "int64",
            "sourceColumn": "IsFromSejam"
          },
          {
            "name": "IsFromSejamName",
            "dataType": "string",
            "sourceColumn": "IsFromSejamName"
          },
          {
            "name": "PersonTypeId",
            "dataType": "int64",
            "sourceColumn": "PersonTypeId"
          },
          {
            "name": "PersonTypeName",
            "dataType": "string",
            "sourceColumn": "PersonTypeName"
          },
          {
            "name": "First_name",
            "dataType": "string",
            "sourceColumn": "First_name"
          },
          {
            "name": "Last_name",
            "dataType": "string",
            "sourceColumn": "Last_name"
          },
          {
            "name": "PersonName",
            "dataType": "string",
            "sourceColumn": "PersonName"
          },
          {
            "name": "GenderId",
            "dataType": "int64",
            "sourceColumn": "GenderId"
          },
          {
            "name": "CustomerGenderName",
            "dataType": "string",
            "sourceColumn": "CustomerGenderName"
          },
          {
            "name": "MarriedStateId",
            "dataType": "int64",
            "sourceColumn": "MarriedStateId"
          },
          {
            "name": "MarriedStateName",
            "dataType": "string",
            "sourceColumn": "MarriedStateName"
          },
          {
            "name": "MilitaryStateId",
            "dataType": "int64",
            "sourceColumn": "MilitaryStateId"
          },
          {
            "name": "MilitaryStateName",
            "dataType": "string",
            "sourceColumn": "MilitaryStateName"
          },
          {
            "name": "FatherName",
            "dataType": "string",
            "sourceColumn": "FatherName"
          },
          {
            "name": "NationalCode",
            "dataType": "string",
            "sourceColumn": "NationalCode"
          },
          {
            "name": "BirthDate",
            "dataType": "dateTime",
            "sourceColumn": "BirthDate"
          },
          {
            "name": "CustomerAge",
            "dataType": "int64",
            "sourceColumn": "CustomerAge"
          },
          {
            "name": "CustomerAgeRange",
            "dataType": "string",
            "sourceColumn": "CustomerAgeRange"
          },
          {
            "name": "CustomerAgeRangeInt",
            "dataType": "int64",
            "sourceColumn": "CustomerAgeRangeInt"
          },
          {
            "name": "RegistrationDate",
            "dataType": "dateTime",
            "sourceColumn": "RegistrationDate"
          },
          {
            "name": "BirthCityId",
            "dataType": "int64",
            "sourceColumn": "BirthCityId"
          },
          {
            "name": "BirthCityName",
            "dataType": "string",
            "sourceColumn": "BirthCityName"
          },
          {
            "name": "BirthStateName",
            "dataType": "string",
            "sourceColumn": "BirthStateName"
          },
          {
            "name": "RegistrationCityId",
            "dataType": "int64",
            "sourceColumn": "RegistrationCityId"
          },
          {
            "name": "RegistrationCityName",
            "dataType": "string",
            "sourceColumn": "RegistrationCityName"
          },
          {
            "name": "RegistrationStateName",
            "dataType": "string",
            "sourceColumn": "RegistrationStateName"
          },
          {
            "name": "EconomicCode",
            "dataType": "string",
            "sourceColumn": "EconomicCode"
          },
          {
            "name": "StockIntroductionId",
            "dataType": "int64",
            "sourceColumn": "StockIntroductionId"
          },
          {
            "name": "StockIntroductionName",
            "dataType": "string",
            "sourceColumn": "StockIntroductionName"
          },
          {
            "name": "IntroducerGenderId",
            "dataType": "int64",
            "sourceColumn": "IntroducerGenderId"
          },
          {
            "name": "IntroducerGenderName",
            "dataType": "string",
            "sourceColumn": "IntroducerGenderName"
          },
          {
            "name": "IntroducerHomeLocationId",
            "dataType": "int64",
            "sourceColumn": "IntroducerHomeLocationId"
          },
          {
            "name": "IntroducerHomeCityName",
            "dataType": "string",
            "sourceColumn": "IntroducerHomeCityName"
          },
          {
            "name": "IntroducerHomeStateName",
            "dataType": "string",
            "sourceColumn": "IntroducerHomeStateName"
          },
          {
            "name": "JobId",
            "dataType": "int64",
            "sourceColumn": "JobId"
          },
          {
            "name": "JobName",
            "dataType": "string",
            "sourceColumn": "JobName"
          },
          {
            "name": "StockTypeId",
            "dataType": "int64",
            "sourceColumn": "StockTypeId"
          },
          {
            "name": "StockTypeName",
            "dataType": "string",
            "sourceColumn": "StockTypeName"
          },
          {
            "name": "BranchId",
            "dataType": "int64",
            "sourceColumn": "BranchId"
          },
          {
            "name": "BranchName",
            "dataType": "string",
            "sourceColumn": "BranchName"
          },
          {
            "name": "BranchCityID",
            "dataType": "int64",
            "sourceColumn": "BranchCityID"
          },
          {
            "name": "BranchCityName",
            "dataType": "string",
            "sourceColumn": "BranchCityName"
          },
          {
            "name": "BranchStateName",
            "dataType": "string",
            "sourceColumn": "BranchStateName"
          },
          {
            "name": "StartDate",
            "dataType": "dateTime",
            "sourceColumn": "StartDate"
          },
          {
            "name": "MembershipAge",
            "dataType": "string",
            "sourceColumn": "MembershipAge"
          },
          {
            "name": "MembershipAgeYear",
            "dataType": "int64",
            "sourceColumn": "MembershipAgeYear"
          },
          {
            "name": "MembershipAgeMonth",
            "dataType": "int64",
            "sourceColumn": "MembershipAgeMonth"
          },
          {
            "name": "MarketerId",
            "dataType": "int64",
            "sourceColumn": "MarketerId"
          },
          {
            "name": "MarketerName",
            "dataType": "string",
            "sourceColumn": "MarketerName"
          },
          {
            "name": "MarketerGenderName",
            "dataType": "string",
            "sourceColumn": "MarketerGenderName"
          },
          {
            "name": "MarketerIsActiveName",
            "dataType": "string",
            "sourceColumn": "MarketerIsActiveName"
          },
          {
            "name": "MarketerPersonTypeName",
            "dataType": "string",
            "sourceColumn": "MarketerPersonTypeName"
          },
          {
            "name": "InsertUserId",
            "dataType": "int64",
            "sourceColumn": "InsertUserId"
          },
          {
            "name": "InsertUserPersonName",
            "dataType": "string",
            "sourceColumn": "InsertUserPersonName"
          },
          {
            "name": "InsertUserGenderID",
            "dataType": "int64",
            "sourceColumn": "InsertUserGenderID"
          },
          {
            "name": "InsertUserGenderName",
            "dataType": "string",
            "sourceColumn": "InsertUserGenderName"
          },
          {
            "name": "BourseCode",
            "dataType": "string",
            "sourceColumn": "BourseCode"
          },
          {
            "name": "ClientAccountNumber",
            "dataType": "string",
            "sourceColumn": "ClientAccountNumber"
          },
          {
            "name": "Credit",
            "dataType": "decimal",
            "sourceColumn": "Credit"
          },
          {
            "name": "StationCredit",
            "dataType": "decimal",
            "sourceColumn": "StationCredit"
          },
          {
            "name": "IntroducerPersonId",
            "dataType": "int64",
            "sourceColumn": "IntroducerPersonId"
          },
          {
            "name": "IntroducerPersonName",
            "dataType": "string",
            "sourceColumn": "IntroducerPersonName"
          },
          {
            "name": "ClubMemberShipDate",
            "dataType": "dateTime",
            "sourceColumn": "ClubMemberShipDate"
          },
          {
            "name": "Available_bonus",
            "dataType": "double",
            "sourceColumn": "Available_bonus"
          },
          {
            "name": "Reserved_bonus",
            "dataType": "int64",
            "sourceColumn": "Reserved_bonus"
          },
          {
            "name": "IsStockMarketCustomer",
            "dataType": "int64",
            "sourceColumn": "IsStockMarketCustomer"
          },
          {
            "name": "IsKalaCustomer",
            "dataType": "int64",
            "sourceColumn": "IsKalaCustomer"
          },
          {
            "name": "IsEnergyCustomer",
            "dataType": "int64",
            "sourceColumn": "IsEnergyCustomer"
          },
          {
            "name": "IsAtiCustomer",
            "dataType": "int64",
            "sourceColumn": "IsAtiCustomer"
          },
          {
            "name": "CodeAccount",
            "dataType": "string",
            "sourceColumn": "CodeAccount"
          },
          {
            "name": "IsForeigner",
            "dataType": "boolean",
            "sourceColumn": "IsForeigner"
          },
          {
            "name": "CustomerFrom",
            "dataType": "string",
            "sourceColumn": "CustomerFrom"
          },
          {
            "name": "EducationName",
            "dataType": "string",
            "sourceColumn": "EducationName"
          },
          {
            "name": "MonthlySalary",
            "dataType": "decimal",
            "sourceColumn": "MonthlySalary"
          },
          {
            "name": "TransactionLevel",
            "dataType": "string",
            "sourceColumn": "TransactionLevel"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 65 11;automationdw\",",
                "    dbo_DimCustomer = Source{[Schema=\"dbo\",Item=\"DimCustomer\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_DimCustomer,{\"DimCustomerID\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "DimDate",
        "columns": [
          {
            "name": "PersianYearWeek",
            "dataType": "int64",
            "sourceColumn": "PersianYearWeek"
          },
          {
            "name": "PersianYearMaliMahaneh",
            "dataType": "int64",
            "sourceColumn": "PersianYearMaliMahaneh"
          },
          {
            "name": "NimSaleMaliName",
            "dataType": "string",
            "sourceColumn": "NimSaleMaliName"
          },
          {
            "name": "NimSaleMali",
            "dataType": "int64",
            "sourceColumn": "NimSaleMali"
          },
          {
            "name": "MaheMaliName",
            "dataType": "string",
            "sourceColumn": "MaheMaliName"
          },
          {
            "name": "MaheMali",
            "dataType": "int64",
            "sourceColumn": "MaheMali"
          },
          {
            "name": "IsOneDayBefore_HijriHoliday",
            "dataType": "boolean",
            "sourceColumn": "IsOneDayBefore_HijriHoliday"
          },
          {
            "name": "IsOneDayBefore_PersianHoliday",
            "dataType": "boolean",
            "sourceColumn": "IsOneDayBefore_PersianHoliday"
          },
          {
            "name": "IsPersianLeap",
            "dataType": "boolean",
            "sourceColumn": "IsPersianLeap"
          },
          {
            "name": "IsGregorianLeap",
            "dataType": "boolean",
            "sourceColumn": "IsGregorianLeap"
          },
          {
            "name": "PersianWeekOfMonthWithYearMonthName",
            "dataType": "string",
            "sourceColumn": "PersianWeekOfMonthWithYearMonthName"
          },
          {
            "name": "PersianWeekOfMonthWithMonthName",
            "dataType": "string",
            "sourceColumn": "PersianWeekOfMonthWithMonthName"
          },
          {
            "name": "PersianWeekOfMonthNameShort",
            "dataType": "string",
            "sourceColumn": "PersianWeekOfMonthNameShort"
          },
          {
            "name": "PersianWeekOfMonthName",
            "dataType": "string",
            "sourceColumn": "PersianWeekOfMonthName"
          },
          {
            "name": "PersianWeekOfMonthNumber",
            "dataType": "int64",
            "sourceColumn": "PersianWeekOfMonthNumber"
          },
          {
            "name": "PersianHalfYearName",
            "dataType": "string",
            "sourceColumn": "PersianHalfYearName",
            "sortByColumn": "PersianHalfYearCode"
          },
          {
            "name": "PersianHalfYearCode",
            "dataType": "int64",
            "sourceColumn": "PersianHalfYearCode"
          },
          {
            "name": "SeasonName",
            "dataType": "string",
            "sourceColumn": "SeasonName",
            "sortByColumn": "SeasonCode"
          },
          {
            "name": "SeasonCode",
            "dataType": "int64",
            "sourceColumn": "SeasonCode"
          },
          {
            "name": "PersianFullName",
            "dataType": "string",
            "sourceColumn": "PersianFullName"
          },
          {
            "name": "PersianWeekOfYearNo",
            "dataType": "int64",
            "sourceColumn": "PersianWeekOfYearNo"
          },
          {
            "name": "PersianWeekOfYearName",
            "dataType": "string",
            "sourceColumn": "PersianWeekOfYearName"
          },
          {
            "name": "PersianDayOfWeekName",
            "dataType": "string",
            "sourceColumn": "PersianDayOfWeekName"
          },
          {
            "name": "PersianYearMonthName",
            "dataType": "string",
            "sourceColumn": "PersianYearMonthName"
          },
          {
            "name": "PersianYearMonthStr",
            "dataType": "string",
            "sourceColumn": "PersianYearMonthStr"
          },
          {
            "name": "PersianYearMonthStrD",
            "dataType": "string",
            "sourceColumn": "PersianYearMonthStrD"
          },
          {
            "name": "PersianYearMonthInt",
            "dataType": "int64",
            "sourceColumn": "PersianYearMonthInt"
          },
          {
            "name": "PersianStr",
            "dataType": "string",
            "sourceColumn": "PersianStr"
          },
          {
            "name": "PersianMonthName",
            "dataType": "string",
            "sourceColumn": "PersianMonthName",
            "sortByColumn": "PersianMonthNo"
          },
          {
            "name": "PersianDayOfWeekInt",
            "dataType": "int64",
            "sourceColumn": "PersianDayOfWeekInt"
          },
          {
            "name": "PersianMonthDayInt",
            "dataType": "int64",
            "sourceColumn": "PersianMonthDayInt"
          },
          {
            "name": "PersianDayInMonth",
            "dataType": "int64",
            "sourceColumn": "PersianDayInMonth"
          },
          {
            "name": "PersianMonthNo",
            "dataType": "int64",
            "sourceColumn": "PersianMonthNo"
          },
          {
            "name": "PersianYearInt",
            "dataType": "int64",
            "sourceColumn": "PersianYearInt"
          },
          {
            "name": "PersianInt",
            "dataType": "int64",
            "sourceColumn": "PersianInt"
          },
          {
            "name": "GregorianDate",
            "dataType": "dateTime",
            "sourceColumn": "GregorianDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 65 11;automationdw\",",
                "    dbo_DimDate = Source{[Schema=\"dbo\",Item=\"DimDate\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_DimDate,{\"PersianYearWeek\", \"PersianYearMaliMahaneh\", \"NimSaleMaliName\", \"NimSaleMali\", \"MaheMaliName\", \"MaheMali\", \"IsOneDayBefore_HijriHoliday\", \"IsOneDayBefore_PersianHoliday\", \"IsPersianLeap\", \"IsGregorianLeap\", \"PersianWeekOfMonthWithYearMonthName\", \"PersianWeekOfMonthWithMonthName\", \"PersianWeekOfMonthNameShort\", \"PersianWeekOfMonthName\", \"PersianWeekOfMonthNumber\", \"PersianHalfYearName\", \"PersianHalfYearCode\", \"SeasonName\", \"SeasonCode\", \"PersianFullName\", \"PersianWeekOfYearNo\", \"PersianWeekOfYearName\", \"PersianDayOfWeekName\", \"PersianYearMonthName\", \"PersianYearMonthStr\", \"PersianYearMonthStrD\", \"PersianYearMonthInt\", \"PersianStr\", \"PersianMonthName\", \"PersianDayOfWeekInt\", \"PersianMonthDayInt\", \"PersianDayInMonth\", \"PersianMonthNo\", \"PersianYearInt\", \"PersianInt\", \"GregorianDate\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "DimOrderSide",
        "columns": [
          {
            "name": "Id",
            "dataType": "int64",
            "sourceColumn": "Id"
          },
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 65 11;automationdw\",",
                "    dbo_DimOrderSide = Source{[Schema=\"dbo\",Item=\"DimOrderSide\"]}[Data]",
                "in",
                "    dbo_DimOrderSide"
              ]
            }
          }
        ]
      },
      {
        "name": "DimTradingStation",
        "columns": [
          {
            "name": "DimTradingStationID",
            "dataType": "int64",
            "sourceColumn": "DimTradingStationID"
          },
          {
            "name": "TradingStationId",
            "dataType": "int64",
            "sourceColumn": "TradingStationId"
          },
          {
            "name": "TradingStationName",
            "dataType": "string",
            "sourceColumn": "TradingStationName"
          },
          {
            "name": "StockTypeId",
            "dataType": "int64",
            "sourceColumn": "StockTypeId"
          },
          {
            "name": "StockTypeName",
            "dataType": "string",
            "sourceColumn": "StockTypeName"
          },
          {
            "name": "IsOnlineStation",
            "dataType": "int64",
            "sourceColumn": "IsOnlineStation"
          },
          {
            "name": "IsOnlineStationName",
            "dataType": "string",
            "sourceColumn": "IsOnlineStationName"
          },
          {
            "name": "StationType",
            "dataType": "string",
            "sourceColumn": "StationType"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 65 11;automationdw\",",
                "    dbo_DimTradingStation = Source{[Schema=\"dbo\",Item=\"DimTradingStation\"]}[Data]",
                "in",
                "    dbo_DimTradingStation"
              ]
            }
          }
        ]
      },
      {
        "name": "FactTrade",
        "columns": [
          {
            "name": "TradeId",
            "dataType": "int64",
            "sourceColumn": "TradeId"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date"
          },
          {
            "name": "CustomerId",
            "dataType": "int64",
            "sourceColumn": "CustomerId"
          },
          {
            "name": "OrderSideId",
            "dataType": "int64",
            "sourceColumn": "OrderSideId"
          },
          {
            "name": "InstrumentId",
            "dataType": "int64",
            "sourceColumn": "InstrumentId"
          },
          {
            "name": "Quantity",
            "dataType": "int64",
            "sourceColumn": "Quantity"
          },
          {
            "name": "Price",
            "dataType": "double",
            "sourceColumn": "Price"
          },
          {
            "name": "TotalPrice",
            "dataType": "double",
            "sourceColumn": "TotalPrice"
          },
          {
            "name": "TradingStationId",
            "dataType": "int64",
            "sourceColumn": "TradingStationId"
          },
          {
            "name": "BrokerCommission",
            "dataType": "double",
            "sourceColumn": "BrokerCommission"
          },
          {
            "name": "TotalCommission",
            "dataType": "double",
            "sourceColumn": "TotalCommission"
          },
          {
            "name": "bcom",
            "dataType": "double",
            "sourceColumn": "bcom"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Value.NativeQuery(#\"SQL/192 168 65 11;automationdw\", \"SELECT ",
                "\tft.TradeId",
                "\t  ,ft.Date",
                "\t  ,ft.CustomerId",
                "\t  ,ft.OrderSideId",
                "\t  ,ft.InstrumentId",
                "\t  ,ft.Quantity",
                "\t  ,ft.Price",
                "\t  ,ft.TotalPrice",
                "\t  ,ft.TradingStationId",
                "\t  ,ft.BrokerCommission",
                "\t  ,ft.TotalCommission",
                "\t  ,ft.bcom",
                "\t  FROM FactTrade ft",
                "\t  WHERE ft.IsCanceled=0 AND date>='2021-03-21'\")",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "BQTY",
            "expression": "SUMX(FILTER(FactTrade,FactTrade[OrderSideId]=1),FactTrade[Quantity])"
          },
          {
            "name": "SQTY",
            "expression": "SUMX(FILTER(FactTrade,FactTrade[OrderSideId]=2),FactTrade[Quantity])"
          },
          {
            "name": "STP",
            "expression": "SUMX(FILTER(FactTrade,FactTrade[OrderSideId]=2),FactTrade[TotalPrice])"
          },
          {
            "name": "BTP",
            "expression": "SUMX(FILTER(FactTrade,FactTrade[OrderSideId]=1),FactTrade[TotalPrice])"
          },
          {
            "name": "BPAVG",
            "expression": "[BTP]/[BQTY]"
          },
          {
            "name": "SPAVG",
            "expression": "[STP]/[SQTY]"
          },
          {
            "name": "SellProfit",
            "expression": "if([BQTY]=[SQTY],[STP]-[BTP],IF([BQTY]>[SQTY],[STP]-([SQTY]*[BPAVG]),0))"
          },
          {
            "name": "PSellProfit",
            "expression": [
              "",
              "SWITCH(TRUE()",
              ",[BQTY]=[SQTY]&& not ISBLANK([BQTY]) &&  not ISBLANK([SQTY])\t ,([STP]/[BTP])-1",
              ",[BQTY]=[SQTY]&& not ISBLANK([BQTY]) &&  ISBLANK([SQTY])\t ,0",
              ",[BQTY]>[SQTY] &&  not ISBLANK([SQTY])  , ( [STP] / ([SQTY] * [BPAVG] ) ) - 1",
              ",BLANK()",
              "",
              ")",
              "",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ]
      },
      {
        "name": "DimInstrument",
        "columns": [
          {
            "name": "InstrumentId",
            "dataType": "int64",
            "sourceColumn": "InstrumentId"
          },
          {
            "name": "Isin",
            "dataType": "string",
            "sourceColumn": "Isin"
          },
          {
            "name": "InstrumentName",
            "dataType": "string",
            "sourceColumn": "InstrumentName"
          },
          {
            "name": "ShortName",
            "dataType": "string",
            "sourceColumn": "ShortName"
          },
          {
            "name": "SectorId",
            "dataType": "int64",
            "sourceColumn": "SectorId"
          },
          {
            "name": "SubSectorId",
            "dataType": "int64",
            "sourceColumn": "SubSectorId"
          },
          {
            "name": "SectorName",
            "dataType": "string",
            "sourceColumn": "SectorName"
          },
          {
            "name": "SubSectorName",
            "dataType": "string",
            "sourceColumn": "SubSectorName"
          },
          {
            "name": "InstrumentBICategoryName",
            "dataType": "string",
            "sourceColumn": "InstrumentBICategoryName"
          },
          {
            "name": "InstrumentBICategoryID",
            "dataType": "int64",
            "sourceColumn": "InstrumentBICategoryID"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/192 168 65 11;automationdw\",",
                "    dbo_DimInstrument = Source{[Schema=\"dbo\",Item=\"DimInstrument\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_DimInstrument,{\"DimInstrumentID\", \"HashValue\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "HistoricalPortfolio",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date"
          },
          {
            "name": "InstrumentId",
            "dataType": "int64",
            "sourceColumn": "InstrumentId"
          },
          {
            "name": "CustomerId",
            "dataType": "int64",
            "sourceColumn": "CustomerId"
          },
          {
            "name": "Asset",
            "dataType": "int64",
            "sourceColumn": "Asset"
          },
          {
            "name": "Price",
            "dataType": "double",
            "sourceColumn": "Price"
          },
          {
            "name": "TotalPrice",
            "dataType": "double",
            "sourceColumn": "TotalPrice"
          },
          {
            "name": "IsFreez",
            "dataType": "boolean",
            "sourceColumn": "IsFreez"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Value.NativeQuery(#\"SQL/192 168 65 11;TempHistorical\", \"SELECT [Date]",
                "\t  ,di.InstrumentId",
                "      ,[CustomerId]",
                "      ,[Asset]",
                "\t  ,[Price]",
                "      ,[Asset]*[Price] AS TotalPrice",
                "      ,[IsFreez]",
                "  FROM [TempHistorical].[dbo].[HistoricalPortfolio]",
                "  JOIN automationdw.dbo.DimInstrument di ON di.Isin = [InstrumentIsin]",
                "  WHERE Date = (SELECT MAX(date) FROM [TempHistorical].[dbo].[HistoricalPortfolio])\")",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "HPV",
            "expression": "SUM(HistoricalPortfolio[TotalPrice])"
          },
          {
            "name": "TotalProfit",
            "expression": " if([BQTY]=[SQTY]+sum(HistoricalPortfolio[Asset]),[STP]-[BTP]+[HPV],0)"
          },
          {
            "name": "PTotalProfit",
            "expression": "if([BQTY]=[SQTY]+sum(HistoricalPortfolio[Asset]), (([STP]+[HPV]-[BTP])/[BTP]),0)",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "CBStats",
            "expression": [
              " SWITCH(",
              "TRUE(),",
              "[BQTY]=[SQTY] && [SQTY]>0 ,4,",
              "[BQTY]=[SellAndHpQty] && [BQTY]>0 ,1,",
              "[BQTY]>[SellAndHpQty] ,3,",
              "[BQTY]<[SellAndHpQty] ,2,0)"
            ]
          },
          {
            "name": "FilterCBstats",
            "expression": [
              " ",
              "var currentSelection = SELECTEDVALUE(CBStats[id])",
              "var currentClass = HistoricalPortfolio[CBStats]",
              "return",
              "SWITCH(TRUE(),",
              "currentSelection = 1 && currentClass = 1,1",
              ",currentSelection = 3 && currentClass = 3,1",
              ",currentSelection = 2 && currentClass = 2,1",
              ",currentSelection = 4 && currentClass = 4,1",
              ",currentSelection = 5 && ( currentClass = 4 || currentClass = 1),1",
              ",currentSelection = 0 && currentClass >0,1,",
              "0)"
            ]
          },
          {
            "name": "HPQty",
            "expression": " sum(HistoricalPortfolio[Asset])"
          },
          {
            "name": "SellAndHpQty",
            "expression": " [SQTY]+[HPQty]"
          }
        ]
      },
      {
        "name": "CBStats",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "ID",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[ID]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Name",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Name]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "SELECTCOLUMNS({(1,\"Remain\"),(2,\"CBIn\"),(3,\"CBOut\"),(4,\"Trade\"),(5,\"T&R\")},\"ID\",[Value1],\"Name\",[Value2])"
            }
          }
        ]
      },
      {
        "name": "LastUpdate",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "ID",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[ID]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Name",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Name]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Type",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Type]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "SELECTCOLUMNS({(1,CALCULATE(max(DimDate[PersianStr]),filter(DimDate,DimDate[GregorianDate]=max(FactTrade[Date]))),\"FT\"),(2,CALCULATE(max(DimDate[PersianStr]),FILTER(DimDate,DimDate[GregorianDate]=max(HistoricalPortfolio[Date]))),\"HP\")",
                "},\"ID\",[Value1],\"Name\",[Value2],\"Type\",[Value3])"
              ]
            }
          }
        ]
      },
      {
        "name": "LeftCustomerByChangeBrokerDetail",
        "columns": [
          {
            "name": "id",
            "dataType": "int64",
            "sourceColumn": "id"
          },
          {
            "name": "assetValue",
            "dataType": "double",
            "sourceColumn": "assetValue"
          },
          {
            "name": "customerId",
            "dataType": "int64",
            "sourceColumn": "customerId"
          },
          {
            "name": "date",
            "dataType": "dateTime",
            "sourceColumn": "date"
          },
          {
            "name": "instrumentId",
            "dataType": "int64",
            "sourceColumn": "instrumentId"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Value.NativeQuery(#\"SQL/192 168 65 11;rawdb\", \"SELECT [id]",
                "      ,[assetValue]",
                "      ,[customerId]",
                "      ,[date]",
                "      ,[instrumentId]",
                "  FROM [RawDB].[bi].[LeftCustomerByChangeBrokerDetail]",
                "  WHERE date >='2023-03-21'\")",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "sumAssetValue",
            "expression": "sum(LeftCustomerByChangeBrokerDetail[assetValue])"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "7ab34610-0801-44ea-aba4-15820cadd434",
        "fromTable": "FactTrade",
        "fromColumn": "CustomerId",
        "toTable": "DimCustomer",
        "toColumn": "CustomerId"
      },
      {
        "name": "c94f85a5-7bc6-49fc-aabd-7beed9bc60cd",
        "fromTable": "FactTrade",
        "fromColumn": "TradingStationId",
        "toTable": "DimTradingStation",
        "toColumn": "TradingStationId"
      },
      {
        "name": "7c644883-8cff-41f3-b09a-74a8cf896eaf",
        "fromTable": "FactTrade",
        "fromColumn": "OrderSideId",
        "toTable": "DimOrderSide",
        "toColumn": "Id"
      },
      {
        "name": "787e4fb3-1bdd-4c38-8c77-8f6961b6ddce",
        "fromTable": "FactTrade",
        "fromColumn": "Date",
        "toTable": "DimDate",
        "toColumn": "GregorianDate"
      },
      {
        "name": "4c417c9c-f2e3-46d5-affa-7bf1b477d5bc",
        "fromTable": "HistoricalPortfolio",
        "fromColumn": "CustomerId",
        "toTable": "DimCustomer",
        "toColumn": "CustomerId"
      },
      {
        "name": "8a9122e7-3061-433d-8bff-00c5550968d2",
        "fromTable": "HistoricalPortfolio",
        "fromColumn": "InstrumentId",
        "toTable": "DimInstrument",
        "toColumn": "InstrumentId"
      },
      {
        "name": "4e4c95a0-21b8-4fd9-880f-51fa35452afb",
        "fromTable": "FactTrade",
        "fromColumn": "InstrumentId",
        "toTable": "DimInstrument",
        "toColumn": "InstrumentId"
      },
      {
        "name": "04e92729-7868-43a3-9ad4-5b661ea2c25c",
        "fromTable": "LeftCustomerByChangeBrokerDetail",
        "fromColumn": "customerId",
        "toTable": "DimCustomer",
        "toColumn": "CustomerId",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "b66ce270-bf17-4a15-af5f-87e0cda4ddeb",
        "fromTable": "LeftCustomerByChangeBrokerDetail",
        "fromColumn": "date",
        "toTable": "DimDate",
        "toColumn": "GregorianDate"
      },
      {
        "name": "4790c0ef-35b7-4db0-99b3-233a4c48ca23",
        "fromTable": "LeftCustomerByChangeBrokerDetail",
        "fromColumn": "instrumentId",
        "toTable": "DimInstrument",
        "toColumn": "InstrumentId"
      }
    ],
    "roles": [
      {
        "name": "Role",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "MOBINSB\\mohammadi",
            "memberId": "S-1-5-21-3822129907-3160699986-3747733816-1145"
          },
          {
            "memberName": "MOBINSB\\M.Rasouli",
            "memberId": "S-1-5-21-3822129907-3160699986-3747733816-6545"
          }
        ]
      }
    ],
    "expressions": [
      {
        "name": "HistoricalPortfolio",
        "kind": "m",
        "expression": [
          "let",
          "    Source = Value.NativeQuery(#\"SQL/192 168 65 11;TempHistorical\", \"SELECT [Date]",
          "\t  ,di.InstrumentId",
          "      ,[CustomerId]",
          "      ,[Asset]",
          "\t  ,[Price]",
          "      ,[Asset]*[Price] AS TotalPrice",
          "      ,[IsFreez]",
          "  FROM [TempHistorical].[dbo].[HistoricalPortfolio]",
          "  JOIN automationdw.dbo.DimInstrument di ON di.Isin = [InstrumentIsin]",
          "  WHERE Date = (SELECT MAX(date) FROM [TempHistorical].[dbo].[HistoricalPortfolio])\")",
          "in",
          "    Source"
        ]
      },
      {
        "name": "LeftCustomerByChangeBrokerDetail",
        "kind": "m",
        "expression": [
          "let",
          "    Source = Value.NativeQuery(#\"SQL/192 168 65 11;rawdb\", \"SELECT [id]",
          "      ,[customerId]",
          "      ,[date]",
          "      ,[instrumentId],[assetValue]",
          "  FROM [RawDB].[bi].[LeftCustomerByChangeBrokerDetail]",
          "  WHERE date >='2023-03-21'\")",
          "in",
          "    Source"
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "600"
      }
    ]
  },
  "id": "SemanticModel"
}